name: therealdanpage
favicon: null
layout_spectrum: 0.42839
typography_spectrum: 0.5731687052175403
title: TheRealDanPage
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.5576512520201504
  lightness: 0.0563299017958343
  saturation: 0.2943394889589399
  rhythmicContrast: 0.24899650714360178
purpose: []
